version: '3.3'
services:
    database:
        image: 'mariadb:10.7.1'
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: main
        ports:
            - '3306'
    phpmyadmin:
        depends_on:
            - database
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            PMA_HOST: database
volumes:
    ###> doctrine/doctrine-bundle ###
    db-data:
###< doctrine/doctrine-bundle ###