<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEbbpxXf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEbbpxXf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEbbpxXf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEbbpxXf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEbbpxXf\App_KernelDevDebugContainer([
    'container.build_hash' => 'EbbpxXf',
    'container.build_id' => '359c9a23',
    'container.build_time' => 1654161192,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEbbpxXf');
