<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXJgq3AK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXJgq3AK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXJgq3AK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXJgq3AK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXJgq3AK\App_KernelDevDebugContainer([
    'container.build_hash' => 'XJgq3AK',
    'container.build_id' => '0e46b1cb',
    'container.build_time' => 1654163856,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXJgq3AK');
